### ISSUE TITLE
registerHelpers not working

### ISSUE THREAD

**Issue by RobLoach** [jonschlinkert/engine#2]
`upper` is not found in the latest code from `master`.

**Comment by doowb** [comment]
Do you have an example of the error you're getting?

`upper` isn't something that's built in, it's in [template-helpers](https://github.com/jonschlinkert/template-helpers) and is only used in the examples here.

**Comment by RobLoach** [comment]
Oops, submitted this to the wrong project. This is an issue for https://github.com/jstransformers/jstransformer-engine .

[template-helpers](https://github.com/jonschlinkert/template-helpers) does look like a good one though!

**Comment by RobLoach** [comment]
In case you're wondering, the code is at https://github.com/jstransformers/jstransformer-engine/blob/master/index.js .
